# Use root/example as user/password credentials
version: "3.1"

services:
  MySqlDatabase:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ""
